## Physics changes

## Not everything is LAr
/edep/phys/ionizationModel 0

/edep/hitSeparation volTPCActive -1 mm
/edep/hitSagitta drift 1.0 mm
/edep/hitLength drift 1.0 mm

/edep/db/set/neutronThreshold 0 MeV
/edep/db/set/lengthThreshold 0 mm
/edep/db/set/gammaThreshold 0 MeV

/edep/random/timeRandomSeed

/edep/update

/generator/kinematics/set bomb
/generator/kinematics/bomb/config mpvmpr/mpvmpr_nd.yaml
/generator/position/set free
/generator/time/set free
/generator/count/fixed/number 1
/generator/count/set fixed
/generator/add
